baseURL = 'https://article.linzh.me/'
languageCode = 'zh'
title = '澪之宮'
theme = "diary"
copyright = "Copyright 2023 - All Rights Reserved by Linzh"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

[params]
subtitle = "指尖點啟 即為永恆"
enableGitalk = true

# Twitter Card and Open Graph settings
# enableOpenGraph = true
# enableTwitterCards = true
# title = "My Blog" # will set 'og:site_name'
# description = "My HomePage Description"  # will set 'og:description'

# [params.gitalk]
#   owner = "Linzh7"
#   repo = "repo name"
#   client_id = "your client id"
#   client_secret = "your client secret"
[taxonomies]
   tag = "tags"
   category = "categories"

# [params.utterances]
# repo="your repo"
# term="[ENTER TERM HERE]"
# label="your label"
# theme="github-light"
[[menu.main]]
url = "/posts"
name = "Posts"
weight = 1
[[menu.main]]
url = "/categories"
name = "Categories"
weight = 5
[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 99
